### ISSUE TITLE
metadata upload issue

### ISSUE THREAD

**Issue by player1122ez** [We-Bump/Lighthouse-cli#2]
it would be nice, if lighthouse cli users could upload additional nft pics and metadata from the same collection many times after first try. When i read medium tutorial first time, i thought its possible by default, but its not. If you create additional nft pics and related json files and try to continue uploading, it returns another token uri then the first time, even if it asks me to "use cache file from previous content".
**2nd Q**: can you do another contract, so users can execute "mint_native" with extra "image_url" field for nft token? it would be really nice ^_^ ( sometime you need custom pictures to mint)

**Comment by sinancino** [comment]
lfg

**Comment by celsosa** [comment]
> it would be nice, if lighthouse cli users could upload additional nft pics and metadata from the same collection many times after first try. When i read medium tutorial first time, i thought its possible by default, but its not. If you create additional nft pics and related json files and try to continue uploading, it returns another token uri then the first time, even if it asks me to "use cache file from previous content". **2nd Q**: can you do another contract, so users can execute "mint_native" with extra "image_url" field for nft token? it would be really nice ^_^ ( sometime you need custom pictures to mint)

update the metadata url for the collection doesn't fix your problem?
